/*
 * JS for Screen1_314_16 generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '28b805d4-0cb6-47c3-ba4c-e8a18ad0fc32';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Screen1_314_16",
    "location": "Screen1_314_16.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

function Screen1_314_16_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_17': 'Screen1_314_16_mobilebutton_17',
        'mobilebutton_18': 'Screen1_314_16_mobilebutton_18',
        'mobilebutton_19': 'Screen1_314_16_mobilebutton_19',
        'mobilebutton_20': 'Screen1_314_16_mobilebutton_20',
        'mobilebutton_21': 'Screen1_314_16_mobilebutton_21',
        'mobilebutton_22': 'Screen1_314_16_mobilebutton_22'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'Screen1_314_16';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var Screen1_314_16_onLoad = function() {
        Screen1_314_16_elementsExtraJS();
        Screen1_314_16_deviceEvents();
        Screen1_314_16_windowEvents();
        Screen1_314_16_elementsEvents();
    };
    // screen window events
    function Screen1_314_16_windowEvents() {
        $('#Screen1_314_16').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function Screen1_314_16_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function Screen1_314_16_elementsExtraJS() {
        // screen (Screen1_314_16) extra code
    };
    // screen elements handler
    function Screen1_314_16_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#Screen1_314_16").on("pagebeforeshow", "#Screen1_314_16", function(event, ui) {
        Apperyio.CurrentScreen = "Screen1_314_16";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    Screen1_314_16_onLoad();
};
$(document).off("pagecreate", "#Screen1_314_16").on("pagecreate", "#Screen1_314_16", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Screen1_314_16_js();
});