/*
 * JS for startScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '28b805d4-0cb6-47c3-ba4c-e8a18ad0fc32';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "Screen1_314_16",
    "location": "Screen1_314_16.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "Screen2_315_16",
    "location": "Screen2_315_16.html"
}];

function startScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_5': 'startScreen_mobilelabel_5',
        'mobilebutton_2': 'startScreen_mobilebutton_2',
        'mobilebutton_4': 'startScreen_mobilebutton_4',
        'mobilebutton_16': 'startScreen_mobilebutton_16',
        'mobileimage_7': 'startScreen_mobileimage_7',
        'mobilelabel_8': 'startScreen_mobilelabel_8',
        'spacer_17': 'startScreen_spacer_17',
        'mobilelabel_12': 'startScreen_mobilelabel_12',
        'mobilelabel_13': 'startScreen_mobilelabel_13',
        'mobilelabel_14': 'startScreen_mobilelabel_14'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_onLoad = function() {
        startScreen_elementsExtraJS();
        startScreen_deviceEvents();
        startScreen_windowEvents();
        startScreen_elementsEvents();
    };
    // screen window events
    function startScreen_windowEvents() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code
    };
    // screen elements handler
    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Screen1_314_16', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_2"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Screen2_315_16', {
                        transition: 'slideup',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_4"]');
        $(document).off("click", '#startScreen_mobilefooter [name="mobilebutton_16"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="startScreen_panel_6"]').panel("open");
                }
            },
        }, '#startScreen_mobilefooter [name="mobilebutton_16"]');
    };
    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_onLoad();
};
$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});